/**
 * extract.mjs — stub. Generated by scripts/docgen/bundle-gate.mjs; do not edit.
 *
 * The workspace module of this name walks a repository mirror and is not part
 * of the gate runner. It appears here because `gate.mjs` imports
 * `isRestrictedPath` from it, and `gate.mjs` is vendored byte for byte.
 *
 * The predicate re-exported here is the UNIVERSAL one: credential directories,
 * credential filenames, key extensions, path traversal. The workspace binds the
 * same factory with a second list naming its own private trees, and that list
 * is deliberately absent from this bundle — publishing an inventory of the
 * directories too sensitive to document would be the disclosure hard gate H1
 * exists to prevent.
 *
 * The consequence is stated rather than hidden: this runner cannot fail a page
 * for naming a private workspace path, because it does not know those paths.
 * The daemon's own gate does, runs first, and refuses to write the page.
 * MANIFEST.json records which deny list this bundle carries as `deny_list_id`.
 */

export { isRestrictedPath } from './restricted.mjs';
